/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health/ping": {
    get: operations["HealthController_getPing"];
  };
  "/categories": {
    /** Get all categories */
    get: operations["CategoriesController_getAllCategories"];
    /** Create a category */
    post: operations["CategoriesController_createCategory"];
  };
  "/categories/{id}": {
    /** Get a category by id */
    get: operations["CategoriesController_getCategory"];
    /** Delete a category by id */
    delete: operations["CategoriesController_deleteCategory"];
    /** Replace a category by id */
    patch: operations["CategoriesController_updateCategory"];
  };
  "/categories/rank": {
    /** order the categories' rank */
    patch: operations["CategoriesController_updateRank"];
  };
  "/addons": {
    /** Get all addons */
    get: operations["AddonsController_getAllAddons"];
    /** Create a addon */
    post: operations["AddonsController_createAddon"];
  };
  "/addons/{id}": {
    /** Get a addon by id */
    get: operations["AddonsController_getAddon"];
    /** Replace a addon by id */
    put: operations["AddonsController_updateAddon"];
    /** Delete a addon by id */
    delete: operations["AddonsController_deleteAddon"];
  };
  "/addons/{id}/activate": {
    /** Change addon status to available */
    patch: operations["AddonsController_setAvailable"];
  };
  "/addons/{id}/deactivate": {
    /** Change addon status to unavailable */
    patch: operations["AddonsController_setUnavailable"];
  };
  "/addons/activate/all": {
    /** Make all addons available */
    post: operations["AddonsController_activateAllAddon"];
  };
  "/menus": {
    /** Get all menus */
    get: operations["MenusController_getMenus"];
    /** Create a menu */
    post: operations["MenusController_createMenu"];
    /**
     * Delete menus by ids
     * @description Delete many menus
     */
    delete: operations["MenusController_removeMenus"];
  };
  "/menus/{id}": {
    /** Get a menu by id */
    get: operations["MenusController_getMenuById"];
    /** Replace a menu by id */
    put: operations["MenusController_updateMenuById"];
    /** Delete a menu by id */
    delete: operations["MenusController_removeMenuById"];
  };
  "/menus/{id}/publish": {
    /** Publish a menu by id */
    patch: operations["MenusController_publishMenuById"];
  };
  "/menus/{id}/unpublish": {
    /** Unpublish a menu by id */
    patch: operations["MenusController_unpublishMenuById"];
  };
  "/orders": {
    /** Get all orders */
    get: operations["OrdersController_getOrders"];
    /** Create order */
    post: operations["OrdersController_createOrder"];
  };
  "/orders/{id}": {
    patch: operations["OrdersController_updateOrder"];
  };
  "/orders/{id}/preparing": {
    /** Change order status to preparing */
    patch: operations["OrdersController_preparing"];
  };
  "/orders/{id}/ready_to_serve": {
    /** Change order status to ready to serve */
    patch: operations["OrdersController_readyToServe"];
  };
  "/orders/{id}/done": {
    /** Change order status to done */
    patch: operations["OrdersController_done"];
  };
  "/orders/{id}/cancel": {
    /**
     * Cancel order
     * @description Cancel order and disable addons, ingredients if included
     */
    patch: operations["OrdersController_cancelOrder"];
  };
  "/sessions": {
    /** Get all sessions */
    get: operations["SessionController_getSessions"];
    /** Create a session */
    post: operations["SessionController_createSession"];
  };
  "/sessions/{id}": {
    /** Get a session by id */
    get: operations["SessionController_getSession"];
    /** Delete a session by id */
    delete: operations["SessionController_deleteSession"];
  };
  "/sessions/table/{id}": {
    /** Get a session by table id */
    get: operations["SessionController_getSessionByTable"];
  };
  "/sessions/{id}/finish": {
    /** Finish a session */
    patch: operations["SessionController_finishSession"];
  };
  "/sessions/{id}/orders": {
    /** Get orders by session */
    get: operations["SessionController_getOrdersBySession"];
  };
  "/sessions/{id}/user": {
    /**
     * Updated session user
     * @description user in header will be used as session user
     */
    patch: operations["SessionController_updateSessionUser"];
  };
  "/sessions/{id}/coupon/all": {
    /** Get all redeemable coupon */
    get: operations["SessionController_getCoupons"];
  };
  "/sessions/{id}/coupon": {
    /** Update coupon in session */
    patch: operations["SessionController_updateSessionCoupon"];
  };
  "/ingredients": {
    /** Get all ingredients */
    get: operations["IngredientsController_findAll"];
    /** Create a ingredient */
    post: operations["IngredientsController_create"];
  };
  "/ingredients/{id}": {
    /** Get a ingredient by id */
    get: operations["IngredientsController_findOne"];
    /** Delete a ingredient by id */
    delete: operations["IngredientsController_remove"];
    /** Update a ingredient by id */
    patch: operations["IngredientsController_updateIngredient"];
  };
  "/ingredients/activate/all": {
    /** Make all ingredient available */
    post: operations["IngredientsController_activateAllIngredient"];
  };
  "/coupons": {
    /** Get all coupons */
    get: operations["CouponsController_findAll"];
    /** Create a coupon */
    post: operations["CouponsController_create"];
  };
  "/coupons/{id}": {
    /** Get a coupon by id */
    get: operations["CouponsController_findOne"];
    /** Delete a coupon by id */
    delete: operations["CouponsController_remove"];
    /** Update a coupon by id */
    patch: operations["CouponsController_update"];
  };
  "/tables": {
    /** Get all tables */
    get: operations["TablesController_getTables"];
    /** Create a table */
    post: operations["TablesController_createTable"];
  };
  "/auth/login": {
    /** Login */
    post: operations["AuthController_signIn"];
  };
  "/auth/logout": {
    /** Logout */
    post: operations["AuthController_signOut"];
  };
  "/auth/register": {
    /** Customer's registration */
    post: operations["AuthController_register"];
  };
  "/auth/me": {
    /** Get current user */
    get: operations["AuthController_getMe"];
  };
  "/users": {
    /** Get users */
    get: operations["UsersController_getUsers"];
    /** Create user (for Owner) */
    post: operations["UsersController_createUser"];
    /** Delete user */
    delete: operations["UsersController_deleteUser"];
    /** Update User info */
    patch: operations["UsersController_updateUserInfo"];
  };
  "/users/reset/password": {
    /** Reset user password */
    post: operations["UsersController_updateUser"];
  };
  "/users/{id}/role": {
    /** Update user role */
    patch: operations["UsersController_updateUserRole"];
  };
  "/dashboard/customer_report/{date}": {
    /** Get total registered users */
    get: operations["DashboardController_getDashboard"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    HealthResponseDto: {
      msg: Record<string, never>;
    };
    CreateCategoryDto: {
      /** @description Category title */
      title: string;
    };
    CategorySchema: {
      /** @description Category ID */
      _id: string;
      /** @description Category title */
      title: string;
      /** @description List of Menu */
      menus: string[];
      /** @description Category rank */
      rank: number | null;
      /** Format: date-time */
      created_at: string;
    };
    UpdateCategoryDto: {
      /** @description Category title */
      title?: string;
      menus?: string[];
    };
    RankDto: {
      /** @description Ordered Rank ID */
      rank: string[];
    };
    CreateAddonDto: {
      title: string;
      price: number;
    };
    AddonSchema: {
      /** @description Addon ID */
      _id: string;
      /** @description Addon Title */
      title: string;
      /** @description Addon Price */
      price: number;
      /**
       * Format: date-time
       * @description Addon deletion date
       */
      deleted_at: string | null;
      /**
       * Format: date-time
       * @default 2023-09-28T16:57:12.590Z
       */
      created_at: string;
      /** @description Addon status */
      available: boolean;
    };
    GetAddonDto: {
      /** @description Addon ID */
      _id: string;
      /** @description Addon Title */
      title: string;
      /** @description Addon Price */
      price: number;
      /**
       * Format: date-time
       * @description Addon deletion date
       */
      deleted_at: string | null;
      /**
       * Format: date-time
       * @default 2023-09-28T16:57:12.590Z
       */
      created_at: string;
      /** @description Addon status */
      available: boolean;
      menus_applied: number;
    };
    UpdateAddonDto: {
      title: string;
      price: number;
    };
    MenuDtoForAllMenu: {
      /** @description Menu ID */
      _id: string;
      /** @description Menu Image */
      image: string | null;
      /** @description Menu Title */
      title: string;
      /** @description Menu Description */
      description: string | null;
      /** @description Menu Price */
      price: number;
      /** @description Menu Ingredients ID */
      ingredients: string[];
      /** @description Menu Addons */
      addons: components["schemas"]["AddonSchema"][];
      /**
       * Format: date-time
       * @description Menu Published Date
       */
      published_at: string;
      /**
       * Format: date-time
       * @description Menu Deleted Date
       */
      deleted_at: string | null;
    };
    GetAllMenuResponseDto: {
      /** @description Menu's Category */
      category: components["schemas"]["CategorySchema"];
      /** @description Array of all menu in category */
      menus: components["schemas"]["MenuDtoForAllMenu"][];
    };
    GetMenuByIdResponseDto: {
      /** @description Menu ID */
      _id: string;
      /** @description Menu Image */
      image: string | null;
      /** @description Menu Title */
      title: string;
      /** @description Menu Description */
      description: string | null;
      /** @description Menu Price */
      price: number;
      /** @description Menu Category */
      category: components["schemas"]["CategorySchema"];
      /** @description Menu Ingredients ID */
      ingredients: string[];
      /** @description Menu Addons */
      addons: components["schemas"]["AddonSchema"][];
      /**
       * Format: date-time
       * @description Menu Published Date
       */
      published_at: string;
      /**
       * Format: date-time
       * @description Menu Deleted Date
       */
      deleted_at: string | null;
    };
    CreateMenuDto: {
      /** @description Menu Image */
      image: string | null;
      /** @description Menu Title */
      title: string;
      /** @description Menu Description */
      description: string | null;
      /** @description Menu Price */
      price: number;
      /** @description Menu Category */
      category?: string;
      /** @description Menu Ingredients */
      ingredients: string[];
      /** @description Menu Addons */
      addons: string[];
    };
    MenuSchema: {
      /** @description Menu ID */
      _id: string;
      /** @description Menu image */
      image: string | null;
      /** @description Menu title */
      title: string;
      /** @description Menu description */
      description: string | null;
      /** @description Menu price */
      price: number;
      /** @description Menu category */
      category: string | null;
      /** @description Menu addons */
      addons: string[];
      /** @description Menu ingredients */
      ingredients: string[];
      /**
       * Format: date-time
       * @description Menu publication date
       */
      published_at: string;
      /**
       * Format: date-time
       * @description Menu deletion date
       */
      deleted_at: string | null;
    };
    Orders: {
      /** @description menu is ObjectID */
      menu: string;
      /** @description Array of ObjectID */
      addons?: string[];
      additional_info?: string;
    };
    CreateOrderDto: {
      /** @description session is ObjectID */
      session: string;
      orders: components["schemas"]["Orders"][];
    };
    TablesSchema: {
      /** @description Table ID */
      _id: string;
      /** @description Table number */
      title: string;
      /** Format: date-time */
      created_at: string;
    };
    SessionWithTableDto: {
      /** @description Session ID */
      _id: string;
      /**
       * Format: date-time
       * @description Session creation date
       */
      created_at: string;
      /**
       * Format: date-time
       * @description Session finish date
       */
      finished_at: string | null;
      /** @description Current head user of session */
      user: string | null;
      /** @description Current coupon in session */
      coupon: string | null;
      /** @description Session's Table */
      table: components["schemas"]["TablesSchema"];
      /**
       * Format: date-time
       * @description Session deletion date
       */
      deleted_at: string | null;
    };
    PopulatedCategoryMenuDto: {
      /** @description Menu ID */
      _id: string;
      /** @description Menu image */
      image: string | null;
      /** @description Menu title */
      title: string;
      /** @description Menu description */
      description: string | null;
      /** @description Menu price */
      price: number;
      /** @description Menu category */
      category: components["schemas"]["CategorySchema"] | null;
      /** @description Menu addons */
      addons: string[];
      /** @description Menu ingredients */
      ingredients: string[];
      /**
       * Format: date-time
       * @description Menu publication date
       */
      published_at: string;
      /**
       * Format: date-time
       * @description Menu deletion date
       */
      deleted_at: string | null;
    };
    IngredientSchema: {
      /** @description Ingredient ID */
      _id: string;
      /** @description Ingredient title */
      title: string;
      /** @description Ingredient status */
      available: boolean;
      /** Format: date-time */
      created_at: string;
    };
    OrderCancelResponseDto: {
      reasons: string;
      ingredients: components["schemas"]["IngredientSchema"][];
      addons: components["schemas"]["AddonSchema"][];
      /** Format: date-time */
      cancelled_at: string;
    };
    OrderGetDto: {
      _id: string;
      /**
       * Format: date-time
       * @description Order creation date
       */
      created_at: string;
      /**
       * @description Order status
       * @enum {string}
       */
      status: "IN_QUEUE" | "PREPARING" | "READY_TO_SERVE" | "DONE" | "CANCELLED";
      /** @description Session (table populated) */
      session: components["schemas"]["SessionSchema"] | string;
      /** @description Menu of the order */
      menu: components["schemas"]["MenuSchema"] | string;
      /** @description Array of MenuID */
      addons: components["schemas"]["AddonSchema"][];
      /** @description Additional info */
      additional_info: string;
      cancel: components["schemas"]["OrderCancelResponseDto"] | null;
    };
    UpdateOrderDto: {
      addons: string[];
      additional_info: string;
    };
    OrderCancelSchema: {
      reasons: string;
      ingredients: string[];
      addons: string[];
      /** Format: date-time */
      cancelled_at: string;
    };
    OrdersSchema: {
      _id: string;
      /**
       * Format: date-time
       * @description Order creation date
       */
      created_at: string;
      /**
       * @description Order status
       * @enum {string}
       */
      status: "IN_QUEUE" | "PREPARING" | "READY_TO_SERVE" | "DONE" | "CANCELLED";
      /** @description Session of the order */
      session: components["schemas"]["SessionSchema"] | string;
      /** @description Menu of the order */
      menu: components["schemas"]["MenuSchema"] | string;
      /** @description Addons of the order */
      addons: (string | components["schemas"]["AddonSchema"])[];
      /** @description Additional info */
      additional_info: string;
      cancel: components["schemas"]["OrderCancelSchema"] | null;
    };
    CancelOrderDto: {
      /**
       * @description Ingredients that out of stock (not implemented yet)
       * @default []
       */
      ingredients?: string[];
      /**
       * @description Addons that out of stock
       * @default []
       */
      addons?: string[];
      /**
       * @description Reason for cancel order
       * @default []
       */
      reasons: string[];
    };
    UserSchema: {
      /** @description User ID */
      _id: string;
      /** @description User name */
      username: string;
      /** @description User point */
      point: number;
      /**
       * @description User role
       * @enum {number}
       */
      role: 100 | 50 | 25 | 1;
      /**
       * Format: date-time
       * @description User creation date
       * @default 2023-09-28T16:57:12.598Z
       */
      created_at: string;
      /**
       * Format: date-time
       * @description User deletion date
       */
      deleted_at: string | null;
    };
    CouponSchema: {
      /** @description Coupon ID */
      _id: string;
      /** @description Coupon title */
      title: string;
      /** @description Coupon description */
      description: string;
      /** @description Coupon image */
      image: string;
      /** @description Coupon required menus */
      required_menus: string[];
      /** @description Discount price of the Coupon */
      discount: number;
      /** @description Quota of the coupon */
      quota: number;
      /** @description Number of coupons that have been redeemed */
      redeemed: number;
      /** @description Coupon status */
      activated: boolean;
      /** @description Coupon required point */
      required_point: number;
      /** Format: date-time */
      created_at: string;
    };
    GetSessionDto: {
      /** @description Session ID */
      _id: string;
      /**
       * Format: date-time
       * @description Session creation date
       */
      created_at: string;
      /**
       * Format: date-time
       * @description Session finish date
       */
      finished_at: string | null;
      /** @description Current head user of session */
      user: components["schemas"]["UserSchema"] | null;
      /** @description Current coupon in session */
      coupon: components["schemas"]["CouponSchema"] | null;
      /** @description Session's Table */
      table: components["schemas"]["TablesSchema"];
      /**
       * Format: date-time
       * @description Session deletion date
       */
      deleted_at: string | null;
    };
    CreateSessionDto: {
      /** @description Table ID */
      table: string;
    };
    SessionSchema: {
      /** @description Session ID */
      _id: string;
      /**
       * Format: date-time
       * @description Session creation date
       */
      created_at: string;
      /**
       * Format: date-time
       * @description Session finish date
       */
      finished_at: string | null;
      /** @description Current head user of session */
      user: string | null;
      /** @description Current coupon in session */
      coupon: string | null;
      /** @description Session's Table */
      table: string;
      /**
       * Format: date-time
       * @description Session deletion date
       */
      deleted_at: string | null;
    };
    ReceiptMenuSchema: {
      _id: string;
      title: string;
      price: number;
    };
    ReceiptCouponSchema: {
      _id: string;
      title: string;
      discount: number;
    };
    ReceiptSchema: {
      session: string;
      menus: components["schemas"]["ReceiptMenuSchema"][];
      coupon: components["schemas"]["ReceiptCouponSchema"];
      total_price: number;
      discount_price: number;
      net_price: number;
      /** Format: date-time */
      created_at: string;
    };
    MenusResponseDto: {
      /** @description Menu ID */
      _id: string;
      /** @description Menu image */
      image: string | null;
      /** @description Menu title */
      title: string;
      /** @description Menu description */
      description: string | null;
      /** @description Menu price */
      price: number;
      /** @description Menu category */
      category: string;
      /** @description Menu addons */
      addons: string[];
      /**
       * Format: date-time
       * @description Menu publication date
       */
      published_at: string;
      /**
       * Format: date-time
       * @description Menu deletion date
       */
      deleted_at: string | null;
    };
    OrdersResponseDto: {
      /** @description Order ID (ObjectID) */
      _id: string;
      /** Format: date-time */
      created_at: string;
      /** @enum {string} */
      status: "IN_QUEUE" | "PREPARING" | "READY_TO_SERVE" | "DONE" | "CANCELLED";
      /** @description Session ID */
      session: string;
      /** @description Menu Schema */
      menu: components["schemas"]["MenusResponseDto"];
      /** @description Array of Addons Schema */
      addons: components["schemas"]["AddonSchema"][];
      /** @description Additional info */
      additional_info: string | null;
      cancel: components["schemas"]["OrderCancelResponseDto"] | null;
    };
    OrdersListDto: {
      /** @description table id */
      table: string;
      /** @description total price */
      total_price: number;
      /** @description discount price */
      discount_price: number;
      /** @description net price */
      net_price: number;
      orders: components["schemas"]["OrdersResponseDto"][];
    };
    CouponDto: {
      /** @description Coupon ID */
      _id: string;
      /** @description Coupon title */
      title: string;
      /** @description Coupon description */
      description: string;
      /** @description Coupon image */
      image: string;
      /** @description Coupon required menus */
      required_menus: string[];
      /** @description Discount price of the Coupon */
      discount: number;
      /** @description Quota of the coupon */
      quota: number;
      /** @description Number of coupons that have been redeemed */
      redeemed: number;
      /** @description Coupon status */
      activated: boolean;
      /** @description Coupon required point */
      required_point: number;
      /** Format: date-time */
      created_at: string;
      /** @description The coupon is redeemable or not */
      redeemable: boolean;
    };
    UpdateSessionCouponDto: {
      /** @description Coupon ID */
      coupon_id: string | null;
    };
    CreateIngredientDto: {
      /** @description Ingredient title */
      title: string;
      /** @description Ingredient status */
      available: boolean;
    };
    GetIngredientDto: {
      /** @description Ingredient ID */
      _id: string;
      /** @description Ingredient title */
      title: string;
      /** @description Ingredient status */
      available: boolean;
      /** Format: date-time */
      created_at: string;
      menus_applied: number;
    };
    UpdateIngredientDto: {
      /** @description Ingredient title */
      title?: string;
      /** @description Ingredient status */
      available?: boolean;
    };
    CreateCouponDto: {
      /** @description Coupon Code */
      title: string;
      /** @description Coupon Description */
      description?: string;
      /** @description Coupon image */
      image?: string;
      required_menus?: string[];
      /** @description Discount price of Coupon */
      discount: number;
      /** @description Quota of the coupon */
      quota: number;
      /** @description Number of coupons that have been redeemed */
      redeemed?: number;
      /** @description Coupon status */
      activated: boolean;
      /** @description Coupon Required Point */
      required_point?: number;
    };
    CouponResponseDTO: {
      /** @description Coupon ID */
      _id: string;
      /** @description Coupon Code */
      title: string;
      /** @description Coupon Description */
      description: string;
      /** @description Coupon image */
      image: string;
      required_menus: components["schemas"]["MenuSchema"][];
      /** @description Discount price of Coupon */
      discount: number;
      /** @description Quota of the coupon */
      quota: number;
      /** @description Number of coupons that have been redeemed */
      redeemed: number;
      /** @description Coupon status */
      activated: boolean;
      /** @description Coupon Required Point */
      required_point: number;
    };
    UpdateCouponDto: {
      /** @description Coupon Code */
      title?: string;
      /** @description Coupon Description */
      description?: string;
      /** @description Coupon image */
      image?: string;
      required_menus?: string[];
      /** @description Discount price of Coupon */
      discount?: number;
      /** @description Quota of the coupon */
      quota?: number;
      /** @description Number of coupons that have been redeemed */
      redeemed?: number;
      /** @description Coupon status */
      activated?: boolean;
      /** @description Coupon Required Point */
      required_point?: number;
    };
    TablesDto: {
      /** @description Table number */
      title: string;
    };
    LoginDto: {
      username: string;
      password: string;
    };
    LoginResponseDto: {
      /**
       * @description JWT access token
       * @example eyJ ...
       */
      access_token: string;
    };
    RegisterDto: {
      /** @description Username */
      username: string;
      /** @description Password */
      password: string;
    };
    UserResponseDto: {
      /** @description User ID */
      _id: string;
      /** @description Username */
      username: string;
      /** @description Role of user */
      role: string;
      point: number;
    };
    CreateUserDto: {
      /** @description Username */
      username: string;
      /** @description Password */
      password: string;
      /**
       * @description select role from enum UserRole example: Owner, Chef, Cashier, Employee, Customer
       * @example Owner
       * @enum {string}
       */
      role: "Owner" | "Cashier" | "Employee" | "Customer";
    };
    UpdateRoleDto: {
      /**
       * @description select role from enum UserRole example: Owner, Cashier, Employee, Customer
       * @example Owner
       * @enum {string}
       */
      role: "Owner" | "Cashier" | "Employee" | "Customer";
    };
    UpdateInfoDto: {
      /** @description New Username */
      newUsername: string;
      /** @description Old Password */
      oldPassword: string;
      /** @description New Password */
      newPassword: string;
    };
    GetUserAmountDto: {
      /** @description Total registered users */
      total_user: number;
      /** @description Total old registered users */
      old_user: number;
      /** @description Total new registered users */
      new_user: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  HealthController_getPing: {
    responses: {
      /** @description Health status */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponseDto"];
        };
      };
    };
  };
  /** Get all categories */
  CategoriesController_getAllCategories: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CategorySchema"][];
        };
      };
    };
  };
  /** Create a category */
  CategoriesController_createCategory: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCategoryDto"];
      };
    };
    responses: {
      /** @description Created new category */
      201: {
        content: {
          "application/json": components["schemas"]["CategorySchema"];
        };
      };
    };
  };
  /** Get a category by id */
  CategoriesController_getCategory: {
    parameters: {
      path: {
        /** @description Category ID (ObjectID) */
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CategorySchema"];
        };
      };
      /** @description Category not found */
      404: never;
    };
  };
  /** Delete a category by id */
  CategoriesController_deleteCategory: {
    parameters: {
      path: {
        /** @description Category ID (ObjectID) */
        id: string;
      };
    };
    responses: {
      204: never;
      /** @description Category not found */
      404: never;
    };
  };
  /** Replace a category by id */
  CategoriesController_updateCategory: {
    parameters: {
      path: {
        /** @description Category ID (ObjectID) */
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCategoryDto"];
      };
    };
    responses: {
      /** @description Update category */
      200: {
        content: {
          "application/json": components["schemas"]["CategorySchema"];
        };
      };
      /** @description Category not found */
      404: never;
    };
  };
  /** order the categories' rank */
  CategoriesController_updateRank: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RankDto"];
      };
    };
    responses: {
      /** @description Change category rank */
      204: never;
    };
  };
  /** Get all addons */
  AddonsController_getAllAddons: {
    parameters: {
      query: {
        status: "active" | "all";
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GetAddonDto"][];
        };
      };
    };
  };
  /** Create a addon */
  AddonsController_createAddon: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAddonDto"];
      };
    };
    responses: {
      /** @description Created addon */
      201: {
        content: {
          "application/json": components["schemas"]["AddonSchema"];
        };
      };
    };
  };
  /** Get a addon by id */
  AddonsController_getAddon: {
    parameters: {
      path: {
        /** @description Addon ID (ObjectID) */
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GetAddonDto"];
        };
      };
      /** @description Addon not found */
      404: never;
    };
  };
  /** Replace a addon by id */
  AddonsController_updateAddon: {
    parameters: {
      path: {
        /** @description Addon ID (ObjectID) */
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAddonDto"];
      };
    };
    responses: {
      /** @description Updated addon */
      200: {
        content: {
          "application/json": components["schemas"]["AddonSchema"];
        };
      };
      /** @description Addon not found */
      404: never;
    };
  };
  /** Delete a addon by id */
  AddonsController_deleteAddon: {
    parameters: {
      path: {
        /** @description Addon ID (ObjectID) */
        id: string;
      };
    };
    responses: {
      204: never;
      /** @description Addon not found */
      404: never;
    };
  };
  /** Change addon status to available */
  AddonsController_setAvailable: {
    parameters: {
      path: {
        /** @description Addon ID (ObjectID) */
        id: string;
      };
    };
    responses: {
      204: never;
    };
  };
  /** Change addon status to unavailable */
  AddonsController_setUnavailable: {
    parameters: {
      path: {
        /** @description Addon ID (ObjectID) */
        id: string;
      };
    };
    responses: {
      204: never;
    };
  };
  /** Make all addons available */
  AddonsController_activateAllAddon: {
    responses: {
      /** @description All addons is now available */
      204: never;
    };
  };
  /** Get all menus */
  MenusController_getMenus: {
    parameters: {
      query: {
        status: "published" | "draft" | "all";
      };
    };
    responses: {
      /** @description Get all menus */
      200: {
        content: {
          "application/json": components["schemas"]["GetAllMenuResponseDto"][];
        };
      };
    };
  };
  /** Create a menu */
  MenusController_createMenu: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMenuDto"];
      };
    };
    responses: {
      /** @description The menu has been successfully created. */
      201: {
        content: {
          "application/json": components["schemas"]["MenuSchema"];
        };
      };
    };
  };
  /**
   * Delete menus by ids
   * @description Delete many menus
   */
  MenusController_removeMenus: {
    parameters: {
      query: {
        ids: string[];
      };
    };
    responses: {
      /** @description The menus have been successfully deleted. */
      200: never;
      /** @description No menu found */
      204: never;
    };
  };
  /** Get a menu by id */
  MenusController_getMenuById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GetMenuByIdResponseDto"];
        };
      };
      /** @description No menu found */
      404: never;
    };
  };
  /** Replace a menu by id */
  MenusController_updateMenuById: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMenuDto"];
      };
    };
    responses: {
      /** @description The menu has been successfully updated. */
      200: never;
      /** @description No menu found */
      404: never;
    };
  };
  /** Delete a menu by id */
  MenusController_removeMenuById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description The menu has been successfully deleted. */
      200: never;
      /** @description No menu found */
      204: never;
    };
  };
  /** Publish a menu by id */
  MenusController_publishMenuById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description The menu has been successfully published. */
      200: never;
      /** @description No menu found */
      404: never;
    };
  };
  /** Unpublish a menu by id */
  MenusController_unpublishMenuById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description The menu has been successfully unpublished. */
      200: never;
      /** @description No menu found */
      404: never;
    };
  };
  /** Get all orders */
  OrdersController_getOrders: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["OrderGetDto"][];
        };
      };
    };
  };
  /** Create order */
  OrdersController_createOrder: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrderDto"];
      };
    };
    responses: {
      /** @description Create order */
      201: never;
    };
  };
  OrdersController_updateOrder: {
    parameters: {
      path: {
        /** @description Order ID */
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateOrderDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["OrdersSchema"];
        };
      };
    };
  };
  /** Change order status to preparing */
  OrdersController_preparing: {
    parameters: {
      path: {
        /** @description Order ID (ObjectId) */
        id: string;
      };
    };
    responses: {
      /** @description Set order status to preparing */
      204: never;
    };
  };
  /** Change order status to ready to serve */
  OrdersController_readyToServe: {
    parameters: {
      path: {
        /** @description Order ID (ObjectId) */
        id: string;
      };
    };
    responses: {
      /** @description Set order status to ready to serve */
      204: never;
    };
  };
  /** Change order status to done */
  OrdersController_done: {
    parameters: {
      path: {
        /** @description Order ID (ObjectId) */
        id: string;
      };
    };
    responses: {
      /** @description Set order status to done */
      204: never;
    };
  };
  /**
   * Cancel order
   * @description Cancel order and disable addons, ingredients if included
   */
  OrdersController_cancelOrder: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CancelOrderDto"];
      };
    };
    responses: {
      204: never;
      404: never;
    };
  };
  /** Get all sessions */
  SessionController_getSessions: {
    parameters: {
      query?: {
        finished?: boolean;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GetSessionDto"][];
        };
      };
    };
  };
  /** Create a session */
  SessionController_createSession: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSessionDto"];
      };
    };
    responses: {
      /** @description Session created */
      201: {
        content: {
          "application/json": components["schemas"]["SessionSchema"];
        };
      };
      /** @description Session already exists */
      409: never;
    };
  };
  /** Get a session by id */
  SessionController_getSession: {
    parameters: {
      path: {
        /** @description Session ID (ObjectID) */
        id: string;
      };
    };
    responses: {
      /** @description Session */
      200: {
        content: {
          "application/json": components["schemas"]["GetSessionDto"];
        };
      };
      /** @description Session not found */
      404: never;
    };
  };
  /** Delete a session by id */
  SessionController_deleteSession: {
    parameters: {
      path: {
        /** @description Session ID (ObjectId) */
        id: string;
      };
    };
    responses: {
      /** @description Session deleted */
      204: never;
      /** @description Session not found */
      404: never;
    };
  };
  /** Get a session by table id */
  SessionController_getSessionByTable: {
    parameters: {
      path: {
        /** @description Table ID */
        id: string;
      };
    };
    responses: {
      /** @description Session */
      200: {
        content: {
          "application/json": components["schemas"]["GetSessionDto"];
        };
      };
      /** @description No session found in the table */
      404: never;
    };
  };
  /** Finish a session */
  SessionController_finishSession: {
    parameters: {
      path: {
        /** @description Session ID (ObjectId) */
        id: string;
      };
    };
    responses: {
      /** @description Receipt of session */
      200: {
        content: {
          "application/json": components["schemas"]["ReceiptSchema"];
        };
      };
      /** @description Session not found */
      404: never;
    };
  };
  /** Get orders by session */
  SessionController_getOrdersBySession: {
    parameters: {
      path: {
        /** @description Session ID (ObjectId) */
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["OrdersListDto"];
        };
      };
    };
  };
  /**
   * Updated session user
   * @description user in header will be used as session user
   */
  SessionController_updateSessionUser: {
    parameters: {
      path: {
        /** @description Session ID (ObjectId) */
        id: string;
      };
    };
    responses: {
      /** @description Updated session user */
      204: never;
    };
  };
  /** Get all redeemable coupon */
  SessionController_getCoupons: {
    parameters: {
      path: {
        /** @description Session ID (ObjectId) */
        id: string;
      };
    };
    responses: {
      /** @description Get all redeemable coupon */
      200: {
        content: {
          "application/json": components["schemas"]["CouponDto"][];
        };
      };
    };
  };
  /** Update coupon in session */
  SessionController_updateSessionCoupon: {
    parameters: {
      path: {
        /** @description Session ID (ObjectId) */
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSessionCouponDto"];
      };
    };
    responses: {
      /** @description Coupon is attached to session */
      204: never;
      /** @description Resource conflict (coupon quota has been reached) */
      409: never;
    };
  };
  /** Get all ingredients */
  IngredientsController_findAll: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GetIngredientDto"][];
        };
      };
    };
  };
  /** Create a ingredient */
  IngredientsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateIngredientDto"];
      };
    };
    responses: {
      /** @description Ingredient created */
      201: {
        content: {
          "application/json": components["schemas"]["IngredientSchema"];
        };
      };
      /** @description Ingredient already exists */
      409: never;
    };
  };
  /** Get a ingredient by id */
  IngredientsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GetIngredientDto"];
        };
      };
      /** @description Ingredient not found */
      404: never;
    };
  };
  /** Delete a ingredient by id */
  IngredientsController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Ingredient deleted */
      200: never;
      /** @description Ingredient not found */
      404: never;
    };
  };
  /** Update a ingredient by id */
  IngredientsController_updateIngredient: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateIngredientDto"];
      };
    };
    responses: {
      /** @description Ingredient updated */
      200: {
        content: {
          "application/json": components["schemas"]["IngredientSchema"];
        };
      };
      /** @description Ingredient not found */
      404: never;
      /** @description Ingredient already exists */
      409: never;
    };
  };
  /** Make all ingredient available */
  IngredientsController_activateAllIngredient: {
    responses: {
      /** @description All ingredient is now available */
      204: never;
    };
  };
  /** Get all coupons */
  CouponsController_findAll: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CouponResponseDTO"][];
        };
      };
    };
  };
  /** Create a coupon */
  CouponsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCouponDto"];
      };
    };
    responses: {
      /** @description Coupon created */
      201: {
        content: {
          "application/json": components["schemas"]["CouponSchema"];
        };
      };
    };
  };
  /** Get a coupon by id */
  CouponsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CouponResponseDTO"];
        };
      };
      /** @description Coupon not found */
      404: never;
    };
  };
  /** Delete a coupon by id */
  CouponsController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Coupon deleted */
      200: never;
      /** @description Coupon not found */
      404: never;
    };
  };
  /** Update a coupon by id */
  CouponsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCouponDto"];
      };
    };
    responses: {
      /** @description Coupon updated */
      200: {
        content: {
          "application/json": components["schemas"]["CouponSchema"];
        };
      };
      /** @description Coupon not found */
      404: never;
    };
  };
  /** Get all tables */
  TablesController_getTables: {
    responses: {
      /** @description Get tables */
      200: {
        content: {
          "application/json": components["schemas"]["TablesSchema"][];
        };
      };
    };
  };
  /** Create a table */
  TablesController_createTable: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TablesDto"];
      };
    };
    responses: {
      /** @description Create table */
      201: {
        content: {
          "application/json": components["schemas"]["TablesSchema"];
        };
      };
    };
  };
  /** Login */
  AuthController_signIn: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponseDto"];
        };
      };
    };
  };
  /** Logout */
  AuthController_signOut: {
    responses: {
      204: never;
    };
  };
  /** Customer's registration */
  AuthController_register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["RegisterDto"];
        };
      };
    };
  };
  /** Get current user */
  AuthController_getMe: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserResponseDto"];
        };
      };
    };
  };
  /** Get users */
  UsersController_getUsers: {
    parameters: {
      query?: {
        /** @description User role */
        role?: string;
      };
    };
    responses: {
      /** @description Get users by roles */
      200: {
        content: {
          "application/json": components["schemas"]["UserSchema"][];
        };
      };
    };
  };
  /** Create user (for Owner) */
  UsersController_createUser: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      /** @description Create user */
      201: never;
    };
  };
  /** Delete user */
  UsersController_deleteUser: {
    parameters: {
      query: {
        /** @description User id (ObjectId) */
        id: string;
      };
    };
    responses: {
      204: never;
    };
  };
  /** Update User info */
  UsersController_updateUserInfo: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateInfoDto"];
      };
    };
    responses: {
      204: never;
    };
  };
  /** Reset user password */
  UsersController_updateUser: {
    parameters: {
      query: {
        /** @description User id (ObjectId) */
        id: string;
      };
    };
    responses: {
      204: never;
    };
  };
  /** Update user role */
  UsersController_updateUserRole: {
    parameters: {
      path: {
        /** @description User id (ObjectId) */
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateRoleDto"];
      };
    };
    responses: {
      204: never;
    };
  };
  /** Get total registered users */
  DashboardController_getDashboard: {
    parameters: {
      path: {
        date: number;
      };
    };
    responses: {
      /** @description Total registered users */
      200: {
        content: {
          "application/json": components["schemas"]["GetUserAmountDto"];
        };
      };
    };
  };
}
